<?php

/**
 * @file
 * Provides multiple plugins for the Restaurant Distribution
 */

/**
 * Implements hook_ctools_plugin_directory().
 */ 
function restaurant_plugins_ctools_plugin_directory($module, $plugin) {
  return 'plugins/' . $plugin;
}

/**
 * Implements hook_theme().
 */
function restaurant_plugins_theme() {
  return array(
    'contact_info_pane' => array(
      'variables' => array('address' => NULL, 'phone' => NULL, 'email' => NULL),
      'template' => 'templates/contact-info-pane',
      'file' => 'restaurant_plugins.theme.inc',
    ),
    'logo_site_name_pane' => array(
      'variables' => array(),
      'template' => 'templates/logo-site-name-pane',
      'file' => 'restaurant_plugins.theme.inc',
    ),
    'navigation' => array(
      'variables' => array(),
      'template' => 'templates/navigation',
      'file' => 'restaurant_plugins.theme.inc',
    ),
  );
}

/**
 * Implements hook_preprocess().
 */
function restaurant_plugins_preprocess(&$variables, $hook) {
  if (isset($variables['layout']) && isset($variables['renderer'])) {
    $variables['extra_classes_array'] = array();
    $regions = array_keys($variables['layout']['regions']);
    foreach ($regions as $region) {
      $variables['extra_classes_array'][$region] = array();
      
      // If a region is empty, add an extra class to it.
      if (!isset($variables['display']->panels[$region])) {
        $variables['extra_classes_array'][$region][] = 'panel-pane-region-empty';
      }
    }

    // Make extra classes printable.
    foreach ($variables['extra_classes_array'] as $key => $extra_classes) {
      $variables['extra_classes'][$key] = implode(" ", $extra_classes);
    }
  }
}
